In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5]

array = np.array([1, 2.55, 3.47, 4, 5])

print(array)
print(lista)

In [ ]:
import numpy as np

lista = [1, 2, 3]

array = np.array([1, 2, 3])

novo_array = array + 5

print(novo_array)

# nova_lista = lista + 5

# print(nova_lista)

[6 7 8]


In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array[0::2])

In [9]:
import numpy as np

valores = np.array([20, 25, 30, 35, 40])

lista_valores = valores * 1.1

print(lista_valores)

[22.  27.5 33.  38.5 44. ]


In [ ]:
import numpy as np

valores = np.array([20, 25, 30, 35, 40])


print(np.sum(valores))


valores = np.array([20, 25, 30, 35, 40])


print(np.sum(valores))
print(np.mean(valores))


print(np.max(valores))
print(np.min(valores))

In [ ]:
import numpy as np

valores = np.array([40, 30, 25, 35, 20])


print(np.sort(valores))

In [ ]:
import numpy as np

quantidade = np.array([10, 20, 30, 40])


preco_unit = np.array([5, 10, 15, 20])


print(np.sum(quantidade * preco_unit))


print(np.dot(quantidade, preco_unit))

In [ ]:
import numpy as np

# valores aleatorios


rng = np.random.default_rng()  # random generator


num = rng.random(7) * 10  # entre 0 e 1


print(f"{num:.2f}")  # or print(num)


rng = np.random.default_rng()  # random generator


num = rng.random(7) * 10  # entre 0 e 1

print(num)


rng = np.random.default_rng()  # random generator


dados = rng.integers(low=50, high=200, size=30)

print(dados)

In [ ]:
import numpy as np

# funçoes de estatistica


rng = np.random.default_rng()  # random generator


dados = rng.integers(low=50, high=200, size=30)

np.median(dados)  # mediana
np.percentile(dados)  # percentil


np.std(dados)  # desvio padrão


np.var(dados)  # variancia

In [ ]:
import numpy as np

# filtros e np.where


salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])


media = np.mean(salarios)


print(salarios[salarios > media])


print(salarios[salarios > 4000])


funcionarios = np.where(salarios > media)


print(funcionarios)


print(salarios[funcionarios])


print(np.where(salarios > media, "Acima da média", "Abaixo da Média"))


salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])


ajuste_salario = np.where(
    (salarios >= 3000) & (salarios <= 4500), salarios * 1.1, salarios
)


print(ajuste_salario)

[4000 4500 4000 5000]
[4500 5000]
(array([2, 4, 5, 6]),)
[4000 4500 4000 5000]
['Abaixo da Média' 'Abaixo da Média' 'Acima da média' 'Abaixo da Média'
 'Acima da média' 'Acima da média' 'Acima da média']
[3300. 3850. 4400. 2000. 4950. 4400. 5000.]
