In [ ]:
# Crie um programa que calcule a média do valor de um produto durante os sete dias da semana, os valores de venda são: 127, 90, 201, 150, 210, 220, 115 cada valor representa um dia da semana, calcule a média e exiba o seu valor. dados = [127, 90, 201, 150, 210, 220, 115]
import numpy as np

dados = np.array([127, 90, 201, 150, 210, 220, 115])


print(np.mean(dados))

159.0


In [14]:
# Crie um programa que calcule o valor máximo, o mínimo e a variação dos valores de uma ação durante a semana, os valores da ação foram: 31.40, 31.32, 30.95, 31.20, 31.60, 31.50, esses valores estão em um array.

valor_acao = np.array([31.40, 31.32, 30.95, 31.20, 31.60, 31.50])

maior = np.max(valor_acao)
menor = np.min(valor_acao)

variacao = maior - menor

print(variacao)

0.6500000000000021


In [16]:
#  Crie um programa que calcule o valor de vendas do dia de cada produto, os produtos são a, b, c e os valores são 100, 200 e 50 e a quantidade vendida foi 5, 3 e 2.

quantidade = np.array([5, 3, 2])

valores = np.array([100, 200, 50])

total = np.dot(quantidade, valores)

total_produto = quantidade * valores

print(total_produto)
print(total)

[500 600 100]
1200


In [3]:
# 1

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])

media = np.mean(salarios)

# quantidade = 0

# for i in salarios:
#     if i > media:
#         quantidade += 1
# print(quantidade)

acima_media = np.sum(salarios > media)

print(acima_media)

5


In [2]:
# 2 Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array numpy. Crie um programa que identifique quaisquer tempos de ciclo que estão dois desvios abaixo

import numpy as np
t_ciclos = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])

media = np.mean(t_ciclos)

desvio = np.std(t_ciclos)

# acima = media + 2 * desvio
# abaixo = media - 2 * desvio

cond = (t_ciclos > media + 2 * desvio) | (t_ciclos > media - 2 * desvio)

valores = np.where(cond)

print(t_ciclos[valores])
print(t_ciclos[cond])

[5.5 5.7 5.9 6.  5.8 5.6 5.7 7.2 4.8]
[5.5 5.7 5.9 6.  5.8 5.6 5.7 7.2 4.8]
