In [ ]:
import numpy as np


# Reshape
vendas = np.array(
    [200, 220, 250, 210, 300, 280, 230, 210, 220, 240, 230, 210, 280, 220]
)

vendas_r = np.reshape(vendas, (2, 7))

print(vendas_r.ndim)

print(vendas_r.shape)

print(vendas[1])

print(vendas[0][0])

print(vendas_r.sum(axis=0))

print(vendas_r.sum(axis=1))

In [1]:
import numpy as np

rng = np.random.default_rng(seed=42)

vendas = rng.integers(low=20, high=200, size=30, endpoint=True)

print(vendas)

vendas_semana = np.reshape(vendas, (5, 6))

print(vendas_semana)

total_vendas_semana = vendas_semana.sum(axis=1)

print(total_vendas_semana)

[ 36 160 138  99  98 175  35 146  56  37 115 196 153 157 149 162 112  43
 171 101 110  87  53 187 161 136  92 168 118 100]
[[ 36 160 138  99  98 175]
 [ 35 146  56  37 115 196]
 [153 157 149 162 112  43]
 [171 101 110  87  53 187]
 [161 136  92 168 118 100]]
[706 585 776 709 775]
