In [2]:
import numpy as np

# Você é um gerente de vendas responsavel por três produtos diferentes (Produto A, Produto B, Produto C) nos ultimos 5 dias. As vendas de cada produto foram registradas em um array 2D numpy, onde cada linha representa um produto e cada coluna representa um dia. Sua tarefa é calcular as vendas totais para cada produto em cada dia. Utilize o seguinte array: vendas = np.array([50, 60, 70, 65, 80, 85, 90, 78, 92, 88, 72, 75, 68, 77, 76])

vendas = np.array([50, 60, 70, 65, 80, 85, 90, 78, 92, 88, 72, 75, 68, 77, 76])

produtos = np.reshape(vendas, (3, 5))

venda_total = produtos.sum(axis=0)

print(venda_total)

[207 225 216 234 244]


In [ ]:
import numpy as np

#  Você é um analista de dados em uma empresa e conduziu uma pesquisa de satisfação do cliente durante uma semana. Você pediu aos clientes para classificar seu nível de satisfação com o serviço em uma escala de 0 a 10. Você coletou respostas de 30 clientes por dia durante 7 dias, resultando em um total de 210 respostas. No entanto, os dados que você recebeu estão em um array de 1d de 210 elementos. Reorganize os dados de forma a ter as respostas por dia e faça uma análise descritiva básica, calculando a média geral de satisfação e a média diária.

rng = np.random.default_rng(seed=9)

respostas = rng.integers(low=0, high=10, size=210)

resultado = np.reshape(respostas, (7, 30))


media_geral = np.mean(resultado)

media_diaria = resultado.mean(axis=1)


print(f"A media geral é: {media_geral}")
print(
    f"""A media diaria:
{media_diaria}"""
)
print(resultado)

A media geral é: 4.695238095238095
A media diaria:
[5.46666667 6.         3.9        3.86666667 3.96666667 4.7
 4.96666667]
[[4 8 9 2 1 6 6 7 6 7 9 9 9 8 7 9 0 0 7 4 7 4 9 0 6 0 1 8 2 9]
 [3 7 9 3 9 7 9 2 5 7 9 2 4 7 8 9 2 9 1 8 8 9 8 7 5 5 0 9 9 0]
 [5 3 7 6 5 4 1 7 8 1 4 0 4 1 4 9 1 1 7 2 0 3 1 6 5 7 6 0 0 9]
 [7 7 8 3 5 1 0 5 2 5 8 2 2 1 3 7 6 6 0 8 7 2 5 7 0 0 2 0 6 1]
 [5 7 2 5 6 6 2 5 2 6 2 3 9 7 1 0 0 3 8 0 1 1 2 9 3 6 0 7 5 6]
 [9 5 0 7 5 6 0 5 8 5 4 5 0 3 8 6 2 4 0 6 7 4 6 7 7 6 6 0 3 7]
 [7 8 2 3 9 7 0 8 3 4 7 1 6 7 6 8 9 3 1 2 4 7 5 5 8 0 8 1 8 2]]
